### ISSUE TITLE
Textinsert with comma

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [turnermm/TextInsert#3]
Hi,

is there a possibility to use the comma inside a parameter for the expanded functionality of the textinsert plugin? 
Example:
# @MSG_ACHTUNG_HTML~Vorsicht, Gefahr fehlerhafter Datenverarbeitung~@

The text "Vorsicht, Gefahr fehlerhafter Datenverarbeitung" should be transformed only to one parameter "%1"

Regards Juergen

**Comment by Juergen-aus-Koeln** [comment]
Hi,

i've modified your macro a little bit so that the comma is substituted by "||" and multiline functionality is supported. For this I have defined a new type "MULTI" besides the existing parameters. Here is the new file:

[syntax.zip](https://github.com/turnermm/TextInsert/files/3609295/syntax.zip)

Because I have no experience in GitHub: Perhaps is it possible that _you_ could take it over as a new release?

Best regards
Juergen
